project:
  type: website
  output-dir: docs

website:
  title: "Jason Bernstein's Website"
  navbar:
    right:
      - text: Blog
        href: blog.qmd
  google-analytics: "G-P4CB3L89DN"
format:
  html:
    theme:
      light: cosmo
      dark: solar
    css: styles.css
